baseURL = 'https://temasictfic.github.io/'
languageCode = 'en-us'
title = 'Writings'
theme = 'ccblog'
enableRobotsTXT = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[params]
  description = "Personal blog about programming and technology"
  author = "SÇ"
  github = "temasictfic"
  name = "Your Name"
  avatar = ""

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    title = "Writings"
    [languages.en.params]
      searchPlaceholder = "Search articles..."
      recentTitle = "Recent writings"
      blogNav = "Blog"
      projectsNav = "Projects"

  [languages.tr]
    languageName = "TR"
    weight = 2
    title = "Yazılar"
    [languages.tr.params]
      searchPlaceholder = "Yazı ara..."
      recentTitle = "Son yazılar"
      blogNav = "Blog"
      projectsNav = "Projeler"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = "rose-pine-moon"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]


